### ISSUE TITLE
please confirm access by commenting and closing this issue.

### ISSUE THREAD

**Issue by tokkentakker** [2016-RCAD-GA-Thesis/lgutierrez#1]

**Comment by LFgutierrez** [comment]
I am commenting!

**Comment by LFgutierrez** [comment]
![image](https://cloud.githubusercontent.com/assets/13905419/9453975/5b3d47ee-4a8c-11e5-9231-90f28ced3880.png)

**Comment by LFgutierrez** [comment]
![image](https://cloud.githubusercontent.com/assets/13905419/9453978/62ee8e94-4a8c-11e5-92b9-a5ac19e9cc49.png)
